### ISSUE TITLE
Login works, but mailu says wrong email/password

### ISSUE THREAD

**Issue by daniel-ratz** [heviat/Mailu-OIDC#50]
Hi,

thanks for the latest update. OIDC with authentik doesn't throw any errors as of now. But now i just cannot login with any of my accounts. After successful authentication mailu tells that me "Wrong e-mail or password". I guess this is some kind of misconfiguration from my side, but where? OIDC itself seems to function, but i am trying to authenticate existing users, is this a problem?
I also tried to authenticate using a new user but again i also see "Wrong e-mail or password".

Is there a special attribute the users need to have in authentik?

i am thankful for any help.

**Comment by Encotric** [comment]
Hi,

unfortunately, I can't reproduce your issue by now. Without further information, its hard to understand where the problem occures. Therefore, could you please provide us e.g. logs of the admin container?

**Comment by daniel-ratz** [comment]
Absolutely, here are the admin container logs just after the oidc authentication:
`
admin-1  | 93.231.75.157 - - [25/Jan/2025:13:30:48 +0000] "GET /internal/auth/user HTTP/1.0" 403 213 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
admin-1  | [2025-01-25 13:30:51,264] WARNING in base: Login failed for None from <IP>
`

it seems like the User is "None"?

Here are also the logs from the front container:
`
admin-1     | [2025-01-25 13:33:47,924] WARNING in base: Login failed for None from <IP>
front-1     | <IP> - - [25/Jan/2025:13:33:47 +0000] "GET /sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg HTTP/1.1" 200 2514 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/app.css HTTP/1.0" 200 758 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 2025/01/25 13:33:48 [warn] 30#30: *862 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/1/01/0000000011 while reading upstream, client: 10.10.2.100, server: , request: "GET /static/vendor.css HTTP/1.0", upstream: "http://192.168.203.4:8080/static/vendor.css", host: "10.10.2.109", referrer: "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg"
front-1     | 2025/01/25 13:33:48 [warn] 30#30: *865 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/2/01/0000000012 while reading upstream, client: 10.10.2.100, server: , request: "GET /static/vendor.js HTTP/1.0", upstream: "http://192.168.203.4:8080/static/vendor.js", host: "10.10.2.109", referrer: "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/vendor.css HTTP/1.0" 200 1333741 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/vendor.js HTTP/1.0" 200 586903 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/app.js HTTP/1.0" 200 11511 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/mailu.png HTTP/1.0" 200 4935 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/app.js HTTP/1.0" 304 0 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/fa-solid-900.woff2 HTTP/1.0" 200 78268 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
front-1     | 10.10.2.100 - - [25/Jan/2025:13:33:48 +0000] "GET /static/fa-regular-400.woff2 HTTP/1.0" 200 13224 "https://mail.REDACTED/sso/login?code=a7316148bc914b86b1c9dc412436c287&state=JoIpM4WDHm0uXJOg" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Safari/605.1.15"
`

Does that help you in any way?
we could talk about it in discord (i'm german) if you would like to.

**Comment by PaddyPat** [comment]
Same with pocketid

**Comment by murdantix** [comment]
I have the same problem, I use Shibboleth.

**Comment by Wombosvideo** [comment]
I face this issue too in my test environment. We are working on a fix to release as soon as possible. Given our limited resources, it might take a few days though.

**Comment by Wombosvideo** [comment]
We have fixed a weird inconsistency in the code which might have caused this issue. At the end, I was no longer able to reproduce the bug so there is a good chance it will stop occuring for you as well.

Please test the new release and report back on whether the issue is resolved for you.

**Comment by daniel-ratz** [comment]
Hi, i was already at my computer so i was able to try it out.
I am still getting the same error: "wrong email or password" after getting back from the auth provider.

**Comment by Wombosvideo** [comment]
Try clearing your cookies and cache

**Comment by daniel-ratz** [comment]
Good catch, but i already tried that. I tried it in another browser and also in an incognito tab.
did not work either :(

**Comment by murdantix** [comment]
I confirm that this problem is always present.

**Comment by Encotric** [comment]
Hi, 
I found something else that we forgot to patch after moving from our old fork [Mailu-OpenID](https://github.com/heviat/Mailu-OpenID) to this one. Could you please test again and report back?

Thank you for your patience.

**Comment by PaddyPat** [comment]
https://pocketid.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
admin-1      | [2025-02-13 19:08:05,212] ERROR in app: Exception on /sso/login [GET]
admin-1      | Traceback (most recent call last):
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
admin-1      |     response = self.full_dispatch_request()
admin-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
admin-1      |     rv = self.handle_user_exception(e)
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
admin-1      |     rv = self.dispatch_request()
admin-1      |          ^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
admin-1      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
admin-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1      |   File "/app/mailu/sso/views/base.py", line 75, in login
admin-1      |     return response
admin-1      |            ^^^^^^^^
admin-1      | UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
^Ccanceled

**Comment by PaddyPat** [comment]
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl HTTP/1.1" 200 2512 "https://pocketid.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/vendor.css HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/app.css HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/app.js HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/vendor.js HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/mailu.png HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/fa-solid-900.woff2 HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/fa-regular-400.woff2 HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"

**Comment by murdantix** [comment]
It works now!! Thank you :)

**Comment by daniel-ratz** [comment]
For me it does say now: Could not decrypt id_token

Any ideas?

**Comment by Encotric** [comment]
> ```
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl HTTP/1.1" 200 2512 "https://pocketid.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/vendor.css HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/app.css HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/app.js HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/vendor.js HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/mailu.png HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/fa-solid-900.woff2 HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> front-1      | 10.200.100.1 - - [13/Feb/2025:20:06:11 +0000] "GET /static/fa-regular-400.woff2 HTTP/1.1" 304 0 "https://mailserver.domain.com/sso/login?code=XXXXXxxxxxxxxx&state=YVRnhSSTTflw3cbl" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15"
> ```
> 
> WebUI login: 404 page not found

That is the output of the `front` container, could you please provide us the output of the `admin` container?

**Comment by Encotric** [comment]
> For me it does say now: Could not decrypt id_token
> 
> Any ideas?

Hmm. Good question. Did you use a fresh session (no cookies)? :)
I also remember that at least Keycloak had in the past some issues with id tokens, but Authentik should be fine

**Comment by Wombosvideo** [comment]
You may ask yourself why we encourage you guys to delete cookies. My local issues were no longer reproducible after clearing cookies. But most of you have already tried that before. But please do try again, because @Encotric updated cookie related settings.

**Comment by PaddyPat** [comment]
> > WebUI login: 404 page not found
> 
> This seems to be the output of the `front` container, could you please provide us the output of the `admin` container?

There is no admin log entry.

Admin logs is only, if I enter mail and password (username/pw works fine in Webui and I can access mails)

If I press openid and it signs vi pocketid correctly, I receive 404 in webui

I mean, mail accounts for openid login should exist before ?
In dockermailserver I create the account before and use in openid only the same mail address. This is fine in roundcube

**Comment by Wombosvideo** [comment]
> Admin logs is only, if I enter mail and password (mail/pw works fine in Webui and I can access mails)
> 
> If I click openid and it signs in via pocketid correctly, I receive 404 in webui.

Sounds like a different issue to me, and it sounds like it's related to #54

**Comment by murdantix** [comment]
I couldn't reproduce this error. The login works, and I can access Roundcube as well.  

If the user doesn't exist, Mailu will create a new one. However, if you create a user with `docker exec`, it won't work like an OIDC user, at least based on my tests. Try accessing the database and changing the password of the created user to "openid," then try again.

**Comment by PaddyPat** [comment]
like @murdantix means, I've created in pocketid a new user, new mail and enabled in mailu allow registration (in domain settings) and also allow 3 accounts.

In the admin logs I see last minutes following msg - but again 404 error

[2025-02-14 13:27:52,041] WARNING in utils: [OIDC] has_state: True, is_state_valid: False

**Comment by Encotric** [comment]
> Maybe its related to pocketid...

Ah, I think I found the problem. You are right, it seems to be a problem of PocketID. Our request to PocketID contains a `state` parameter for security reasons. But unfortunately, PocketID seems to ignore such parameters and redirects the user only with the `code` query parameter. Therefore, it might be a good idea to open an issue at PocketID because the `state` is part of the OpenID Connect standard.

**Comment by PaddyPat** [comment]
https://github.com/pocket-id/pocket-id/issues/278#issuecomment-2692381342

**Comment by Wombosvideo** [comment]
Does this mean it works now, but the initial page load after login doesn't?

**Comment by PaddyPat** [comment]
yes, it works but during first login round cube tells "session is expired". had to login again and than I'm logged in.

Maybe you test is by yourself, pocketid is very easy to deploy and realy worth.
https://pocket-id.org/docs/setup/installation

**Comment by PaddyPat** [comment]
@murdantix repeat login via oidc auth and your logged in (this is how pocketid works)

**Comment by murdantix** [comment]
@PaddyPatI believe this is not the intended behavior. Users should be redirected to the webmailer directly after logging in, rather than encountering an error.

**Comment by Wombosvideo** [comment]
> Users should be redirected to the webmailer directly after logging in, rather than encountering an error.

Absolutely, and we're working on that. The problem is that we're unable to reproduce many of the issues you guys are facing. Given our limited resources, we unfortunately cannot test every possible scenario, so we heavily rely on your input, testing and log messages.

**Comment by PaddyPat** [comment]
Yes my maildomain is different to my server hostname…

**Comment by Wombosvideo** [comment]
Can you test the latest version? We now set the redirect URL based on the request URL instead of using the first hostname.

**Comment by redispade** [comment]
> Can you test the latest version? We now set the redirect URL based on the request URL instead of using the first hostname.

I tested logging in with my mail domain(HOSTNAMES variable) and server domain(DOMAIN variable) variable and both authenticate and redirect properly. I use pocket-id

**Comment by murdantix** [comment]
@Wombosvideo I just tested it. After logging into the IDP page, I get redirected back to the login page. If I click the OpenID button again, I get redirected to the same page once more. 

https://github.com/user-attachments/assets/9ef51587-8f12-4e1b-9017-39238aeb3bba

**Comment by Encotric** [comment]
@murdantix Hi, thank you for testing! Could you please provide us the redirect url the "OpenID Connect button is referring to? You can remove e.g. your domain name and replace it with a dummy, of course.

**Comment by murdantix** [comment]
Hi, here ist the link of the button:
https://idp.domail.de/idp/profile/oidc/authorize?client_id=mailuClienID&response_type=code&scope=openid+email&nonce=4mNP4y9jRBaDWPPx&redirect_uri=https%3A%2F%2Fmail.domain.de&state=g6XDPBVemmbxqGbE
in Mailu.env:
###################################
# OpenID Connect settings
###################################

# Enable OpenID Connect. Possible values: True, False
OIDC_ENABLED=true
# OpenID Connect provider configuration URL
OIDC_PROVIDER_INFO_URL=https://idp.domain.de
# OpenID redirect URL if HOSTNAME not matching your login url
OIDC_REDIRECT_URL=https://mail.domain.de
# OpenID Connect Client ID for Mailu
OIDC_CLIENT_ID=mailuClientID
# OpenID Connect Client secret for Mailu
OIDC_CLIENT_SECRET=sercretKey
# Label text for OpenID Connect login button. Default: OpenID Connect
OIDC_BUTTON_NAME=OpenID Connect
# Disable TLS certificate verification for the OIDC client. Possible values: True, False
OIDC_VERIFY_SSL=True

**Comment by Encotric** [comment]
I think the problem might be the `OIDC_REDIRECT_URL=https://mail.domain.de/` in your mailu.env. Seems like this is a historically grown option we don't need anymore. Could you please remove it and try again?

**Comment by PaddyPat** [comment]
OIDC_REDIRECT_URL= was also a issue from me, now I get again "session is invalid on round cube login" and if I again, remove https://mailserver.domain.com/webmail/index.php in browser bar index.php and enter again, I'm logged in in roundcvue in mail-2024-06-16 (https://mailserver.domain.com/webmail/)

**Comment by murdantix** [comment]
After deleting the OIDC_REDIRECT_URL i get the same issue as this https://github.com/heviat/Mailu-OIDC/issues/50#issuecomment-2718152412

**Comment by Wombosvideo** [comment]
If nobody is still facing the original "wrong email/password" issue, I will close this in favor of #60. Please tell us whether this issue is still happening for you @daniel-ratz

**Comment by vo0ov** [comment]
Same problem.

**Comment by Wombosvideo** [comment]
Thank you for your reply, @vo0ov. Can you elaborate on what problems exactly you are facing and tell us a bit more about your setup? Not having any information makes it really hard to reproduce and eventually fix the issue.

**Comment by vo0ov** [comment]
Я просто следовал инструкциям в setup. После запуска с генерированным конфигом админ-пользователь появился, но вход в панель не работал.
